### ISSUE TITLE
NullPointerException on server.MPD.isConnected

### ISSUE THREAD

**Issue by mczerski** [finnyb/javampd#51]
I'm trying to debug connection problems in mpd binding in openhab.  the problem is that sometimes listeners stop notifying, but sending command still works. so i fire server.MPD.isConnected before sending any command to see what is wrong and when there is no notifications from mpd i get NullPointerException on server.MPD.isConnected. included the backtrace at the end.

seems that in server/MPDSocket.java in line 251 reader.readLine() returned null.

paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: 2016-10-24 22:23:39.208 [ERROR] [g.bff.javampd.server.MPDSocket] - Could not determine if response is ok
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: java.lang.NullPointerException: null
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.server.MPDSocket.isResponseOK(MPDSocket.java:146) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.server.MPDSocket.checkConnection(MPDSocket.java:252) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.server.MPDSocket.sendCommand(MPDSocket.java:103) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:59) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:38) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.server.MPD.ping(MPD.java:129) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.bff.javampd.server.MPD.isConnected(MPD.java:124) [javampd-6.0.0-SNAPSHOT.jar:6.0.0-SNAPSHOT]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.binding.mpd.internal.MpdBinding.executePlayerCommand(MpdBinding.java:194) [bundlefile:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.binding.mpd.internal.MpdBinding.internalReceiveCommand(MpdBinding.java:146) [bundlefile:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:97) [org.openhab.core_1.8.3.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42) [org.openhab.core_1.8.3.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.core.internal.events.EventPublisherImpl.sendCommand(EventPublisherImpl.java:56) [org.openhab.core_1.8.3.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.openhab.ui.webapp.internal.servlet.CmdServlet.service(CmdServlet.java:95) [org.openhab.ui.webapp_1.8.3.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet_3.0.0.v201112011016.jar:na]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
paź 24 22:23:39 livingroom-osmc openhab.sh[23190]: at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by finnyb** [comment]
Found some flaws in the way checks for connectivity was happening.  If my latest changes don't help I'll probably experiment with simplifying the way connectivity is being done.

**Comment by mczerski** [comment]
ok, so i use the latest version and will report if the problem still exists. btw. how to run tests ? are thera any preconditions ? couse almost all tests are failing.

**Comment by finnyb** [comment]
unit tests should run without any issues using your ide or mvn test, are you referring to integration tests?  I have a docker container I use for integration testing:

https://cloud.docker.com/app/finnyb/repository/docker/finnyb/javampdit/general

**Comment by mczerski** [comment]
i'm not a java developer so i don't realu know what i'm doing :) i run "mvn clean install" and one of the steps of target install are tests. if i run mvn -Dmaven.test.skip=true clean install then no tests are run and process finish succesfully

**Comment by finnyb** [comment]
Gotcha,  I've moved the integration tests into a separate maven profile so now doing a clean install should only run unit tests.

**Comment by mczerski** [comment]
so far no connection problems so it seems that the problem is solved. and mvn clean install is now ends with success. thanks !

**Comment by mczerski** [comment]
i encoutered another issue, don't now if it is related to this thread.
