### ISSUE TITLE
Player refresh interval not changeable

### ISSUE THREAD

**Issue by Scrumplex** [finnyb/javampd#53]
Hello there,
I just started using this library and noticed that the `Player` class refreshes every 5 second, and that interval is not changeable.

**Comment by finnyb** [comment]
Are you referring to the stand alone monitor thread?  It appears this is set to check every second.  I agree this needs to be made configurable though.  I'll get a fix in shortly.

**Comment by Scrumplex** [comment]
As far as I looked through the code, the Player class gets statuses like `totaltime` and `elapsedtime` from the `Server` class. If I do 
`mpd.getServer().setRefreshInterval(0);` it still refreshes every 5 seconds.

**Comment by finnyb** [comment]
out of curiosity have you tried setting the interval to 1 instead of 0?  The 0 second interval might be throwing the calculation off

**Comment by Scrumplex** [comment]
Yes I also tried that

**Comment by rugarci** [comment]
After this change I get this exception:

017-09-10 12:13:28 INFO  MPDProperties:48 - Override properties file not on classpath
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.bff.javampd.server.MPDProperties.loadProperties(MPDProperties.java:53)
	at org.bff.javampd.server.MPDProperties.loadOverrideValues(MPDProperties.java:46)

Maybe load properties should throw not only IOException
