### ISSUE TITLE
listAllAlbums() messes up albums

### ISSUE THREAD

**Issue by rain0r** [finnyb/javampd#74]
`getMusicDatabase().getAlbumDatabase().listAllAlbums()` unfortunately mixes up the albums.

Here's my code:

```java
    Collection<MPDAlbum> albums = mpd.getMusicDatabase().getAlbumDatabase().listAllAlbums();
    Set<MPDAlbum> alive = albums.stream().filter(
        a -> a.getArtistName().contains("But Alive")
    ).collect(Collectors.toSet());
```

Where `mpd` is an instance of `MPD`.
The set `alive` contains one element of the type `MPDAlbum` with the name `13`.

Unfortunately, there is no album from that band with the name `13`. Its from the previous band in my collection.

Here`s the corresponding mpd command:

```
echo list "album" "group" "artist" "group" "date" "group" "genre" | nc localhost 6600
```

And the output:

```
[...]
Genre: Punk Rock
Date:
Artist: Die Ärzte
Album: 13
Artist: …But Alive
Album: Bis jetzt ging alles gut …
Album: Für uns nicht
Album: Hallo Endorphin
Album: Nicht zynisch werden?!
[...]
```

**Comment by finnyb** [comment]
this should be resolved in release >= 7.0.0
